# This file should be in UTF8 without BOM - Accents examples: éèê
# +----------------------------------------------------------------------+
# | Copyright (c) 2004-2018 Advisto SAS, service PEEL - contact@peel.fr  |
# +----------------------------------------------------------------------+
# | This file is part of PEEL Shopping 9.0.0, which is subject to an	 |
# | opensource GPL license: you are allowed to customize the code		 |
# | for your own needs, but must keep your changes under GPL 			 |
# | More information: https://www.peel.fr/lire/licence-gpl-70.html		 |
# +----------------------------------------------------------------------+
# | Author: Advisto SAS, RCS 479 205 452, France, https://www.peel.fr/	 |
# +----------------------------------------------------------------------+
# $Id: peel_shop.sql 53676 2017-04-25 14:51:39Z sdelaporte $
#
INSERT INTO peel_html (`lang`, `contenu_html`, `etat`, `titre`, `o_timestamp`, `a_timestamp`, `emplacement`, `site_id`) VALUES
('fr', '<div class="col-md-12"> <div class="row"> <div class="col-md-3 col-sm-6 personnalized_footer_block_1"> [NEWSLETTER_FORM] <div class="personnalized_footer_company_logo"> <a href="[WWWROOT]"><img src="[WWWROOT]/upload/logo_footer_Made_with_PEEL.png" alt="logo footer Made with PEEL" /></a> </div> </div> <div class="col-md-3 col-sm-6 personnalized_footer_block_2"> <div> <span style="font-weight:bold;">VOTRE SOCIETE</span><br /> adresss<br /> code postal ville<br /> pays<br /> Tel. XX XX XX XX XX </div> </div> <div class="clearfix visible-sm"></div> <div class="col-md-3 col-sm-6 personnalized_footer_block_3"> <img src="[WWWROOT]/upload/bloc_paypal.png" alt=""> </div> <div class="col-md-3 col-sm-6 personnalized_footer_block_4"> <div class="footer_copyright right"> <div><span><a href="https://www.advisto.fr/">Une création PEEL création de site eCommerce</a></span></div> </div> <div class="footer_custom_social_icons"> <a href="https://fr-fr.facebook.com/" target="_blank"> <img class="footer_custom_address_facebook_logo" src="[WWWROOT]/modeles/peel9/images/facebook.png" alt="Facebook"> </a> <a href="https://twitter.com/?lang=fr" target="_blank"> <img class="footer_custom_address_twitter_logo" src="[WWWROOT]/modeles/peel9/images/twitter.png" alt="Twitter"> </a> <a href="[WWWROOT]/modules/rss/rss.php" onclick="return(window.open(this.href)?false:true);"> <img class="footer_custom_address_rss_logo" src="[WWWROOT]/modeles/peel9/images/rss.png" alt="RSS"> </a> </div> </div> </div> </div> <div class="col-md-12 personnalized_footer_links_block"> <ul class="link"><li><a href="[WWWROOT]/utilisateurs/contact.php">Nous contacter</a></li> <li><a href="[WWWROOT]/legal.php">Informations légales</a></li> <li><a href="[WWWROOT]/cgv.php">Conditions de vente</a></li> <li><a href="[WWWROOT]/plan_acces.php">Plan d''accès</a></li>  </ul> </div>', 1, 'Footer personnalisable', NOW(), NOW(), 'footer_full_custom_html',"[SITE_ID]"),
('en', '<div class="col-md-12"> <div class="row"> <div class="col-md-3 col-sm-6 personnalized_footer_block_1"> [NEWSLETTER_FORM] <div class="personnalized_footer_company_logo"> <a href="[WWWROOT]"><img src="[WWWROOT]/upload/logo_footer_Made_with_PEEL.png" alt="logo footer Made with PEEL" /></a> </div> </div> <div class="col-md-3 col-sm-6 personnalized_footer_block_2"> <div> <span style="font-weight:bold;">YOUR COMPANY</span><br /> address<br /> zip code city<br /> country<br /> Tel. XX XX XX XX XX </div> </div> <div class="clearfix visible-sm"></div> <div class="col-md-3 col-sm-6 personnalized_footer_block_3"> <img src="[WWWROOT]/upload/bloc_paypal.png" alt=""> </div> <div class="col-md-3 col-sm-6 personnalized_footer_block_4"> <div class="footer_copyright right"> <div><span><a href="https://www.advisto.fr/">Created by PEEL eCommerce solution</a></span></div> </div> <div class="footer_custom_social_icons"> <a href="https://fr-fr.facebook.com/" target="_blank"> <img class="footer_custom_address_facebook_logo" src="[WWWROOT]/modeles/peel9/images/facebook.png" alt="Facebook"> </a> <a href="https://twitter.com/?lang=fr" target="_blank"> <img class="footer_custom_address_twitter_logo" src="[WWWROOT]/modeles/peel9/images/twitter.png" alt="Twitter"> </a> <a href="[WWWROOT]/modules/rss/rss.php" onclick="return(window.open(this.href)?false:true);"> <img class="footer_custom_address_rss_logo" src="[WWWROOT]/modeles/peel9/images/rss.png" alt="RSS"> </a> </div> </div> </div> </div> <div class="col-md-12 personnalized_footer_links_block"> <ul class="link"><li><a href="[WWWROOT]/utilisateurs/contact.php">To contact us</a></li> <li><a href="[WWWROOT]/legal.php">Legal informations</a></li> <li><a href="[WWWROOT]/cgv.php">Terms and conditions</a></li> <li><a href="[WWWROOT]/plan_acces.php">Access map</a></li>  </ul> </div>', 1, 'Footer customizable', NOW(), NOW(), 'footer_full_custom_html',"[SITE_ID]"),
('es','<div class="col-md-12"> <div class="row"> <div class="col-md-3 col-sm-6 personnalized_footer_block_1"> [NEWSLETTER_FORM] <div class="personnalized_footer_company_logo"> <a href="[WWWROOT]"><img src="[WWWROOT]/upload/logo_footer_Made_with_PEEL.png" alt="logo footer Made with PEEL" /></a> </div> </div> <div class="col-md-3 col-sm-6 personnalized_footer_block_2"> <div> <span style="font-weight:bold;">TU COMPAÑÍA</span><br /> dirección<br /> código postal ciudad<br /> país<br /> Tel. XX XX XX XX XX </div> </div> <div class="clearfix visible-sm"></div> <div class="col-md-3 col-sm-6 personnalized_footer_block_3"> <img src="[WWWROOT]/upload/bloc_paypal.png" alt=""> </div> <div class="col-md-3 col-sm-6 personnalized_footer_block_4"> <div class="footer_copyright right"> <div><span><a href="https://www.advisto.fr/">Creado por PEEL eCommerce solution</a></span></div> </div> <div class="footer_custom_social_icons"> <a href="https://fr-fr.facebook.com/" target="_blank"> <img class="footer_custom_address_facebook_logo" src="[WWWROOT]/modeles/peel9/images/facebook.png" alt="Facebook"> </a> <a href="https://twitter.com/?lang=fr" target="_blank"> <img class="footer_custom_address_twitter_logo" src="[WWWROOT]/modeles/peel9/images/twitter.png" alt="Twitter"> </a> <a href="[WWWROOT]/modules/rss/rss.php" onclick="return(window.open(this.href)?false:true);"> <img class="footer_custom_address_rss_logo" src="[WWWROOT]/modeles/peel9/images/rss.png" alt="RSS"> </a> </div> </div> </div> </div> <div class="col-md-12 personnalized_footer_links_block"> <ul class="link"><li><a href="[WWWROOT]/utilisateurs/contact.php">Contáctenos</a></li> <li><a href="[WWWROOT]/legal.php">Información legal</a></li> <li><a href="[WWWROOT]/cgv.php">Condiciones de venta</a></li> <li><a href="[WWWROOT]/plan_acces.php">Mapa</a></li></ul> </div>', 1, 'Footer personalizable', NOW(), NOW(), 'footer_full_custom_html', "[SITE_ID]");