# This file should be in UTF8 without BOM - Accents examples: éèê
# +----------------------------------------------------------------------+
# | Copyright (c) 2004-2018 Advisto SAS, service PEEL - contact@peel.fr  |
# +----------------------------------------------------------------------+
# | This file is part of PEEL Shopping 9.0.0, which is subject to an	 |
# | opensource GPL license: you are allowed to customize the code		 |
# | for your own needs, but must keep your changes under GPL 			 |
# | More information: https://www.peel.fr/lire/licence-gpl-70.html		 |
# +----------------------------------------------------------------------+
# | Author: Advisto SAS, RCS 479 205 452, France, https://www.peel.fr/	 |
# +----------------------------------------------------------------------+
# $Id: peel_shop_content.sql 53676 2017-04-25 14:51:39Z sdelaporte $
#
-- configuration

-- zone HTML personnalisable
UPDATE `peel_html` SET `etat` = '0' WHERE (`emplacement` = 'home' OR `emplacement` = 'home_middle' OR `emplacement` = 'home_bottom') AND site_id="[SITE_ID]" AND lang='es';
INSERT INTO `peel_html` (`id`, `contenu_html`, `etat`, `titre`, `o_timestamp`, `a_timestamp`, `emplacement`, `lang`, `site_id`) VALUES
(NULL, '<div class="row text-center eshopping_home_middle_zone">\n<div class="col-md-8 eshopping_home_middle_zone_left_block">\n<div class="eshopping_home_middle_zone_left_block_image">\n<div>\n<p style="font-size: 44px; font-weight: bold; text-transform: uppercase;">Venta de verano</p>\n<p style="font-size: 18px; font-weight: bold;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>\n</div>\n</div>\n</div>\n<div class="col-md-4 eshopping_home_middle_zone_right_block">\n<div class="eshopping_home_middle_zone_right_block_image"></div>\n<div class="eshopping_home_middle_zone_right_block_button_banner"><a href="[WWWROOT]/administrer/html.php" class="btn btn-primary btn_personnalized_two_lines"> 				<span class="glyphicon glyphicon-pencil"> 				</span> 				<span style="font-weight: bold;">Administrar el contenido</span><br />\n<span class="btn_personnalized_second_line">de esta área</span> 			</a></div>\n</div>\n</div>', 1, 'Middle home page', '2017-10-05 14:53:15', '2017-10-05 14:53:15', 'home_middle', 'es', 1),
(NULL, '<p>[CLOSE_MAIN_CONTAINER]</p>\r\n<div class="eshopping_home_welcome_zone_personnalized_banner">\r\n<div class="container">\r\n<div class="row text-center">\r\n<div class="col-md-12">\r\n<div class="eshopping_home_welcome_zone_white_block">\r\n<p style="font-size: 28px;"><span style="font-weight: bold;">Bienvenido</span> a su nuevo sitio!</p>\r\n<p style="font-size: 16px;">Su nuevo sitio es totalmente administrable por usted.<br />\r\nPuede llenar esta área según sus preferencias o elegir no mostrarla.</p>\r\n<a href="[WWWROOT]/administrer/html.php" class="btn btn-primary btn_personnalized_two_lines"> 						<span class="glyphicon glyphicon-pencil"> 						</span> 						<span style="font-weight: bold;">Administrar el contenido</span><br />\r\n<span class="btn_personnalized_second_line">de esta área</span> 					</a></div>\r\n</div>\r\n</div>\r\n</div>\r\n</div>\r\n<p>[REOPEN_MAIN_CONTAINER]</p>', 1, 'Home site content', '2017-07-07 15:58:33', '2017-10-25 17:08:03', 'home', 'es', 1),
(NULL, '<div class="row text-center eshopping_home_prefooter_zone">\n<div class="col-md-8 eshopping_home_prefooter_zone_left_block">\n<div class="eshopping_home_prefooter_zone_left_block_image">\n<div class="eshopping_home_prefooter_zone_button_banner">\n<p>Personaliza esta área</p>\n<a href="[WWWROOT]/administrer/html.php" class="btn btn-primary btn_personnalized_two_lines"> 					<span class="glyphicon glyphicon-pencil"> 					</span> 					<span style="font-weight: bold;">Administrar el contenido</span><br />\n<span class="btn_personnalized_second_line">de esta área</span> 				</a></div>\n</div>\n</div>\n<div class="col-md-4 eshopping_home_prefooter_zone_right_block">\n<div class="eshopping_home_prefooter_zone_right_block_image"></div>\n</div>\n</div>', 1, 'Bas de page du site', '2017-07-07 15:58:33', '2017-10-24 15:10:46', 'home_bottom', 'es', 1);

-- categories
UPDATE peel_categories SET nom_es = '	Ropa ', description_es = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut pretium ultricies pharetra. Etiam eu nisi erat. Fusce quis finibus nibh, non ultrices dolor. Donec a auctor augue, sit amet tempor nulla. Phasellus sapien ante, molestie sed dapibus vitae, rhoncus quis enim. Suspendisse sit amet metus non enim blandit dignissim nec a lectus.&nbsp;</p>', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-vetements-zskpbg.jpg', image_header_es = 'categorie-vetements-xsxhrq.png', alpha_es = '', sentence_displayed_on_product_es = '' WHERE id = 2;
UPDATE peel_categories SET nom_es = 'Comida', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-alimentation-j3evxy.jpg', image_header_es = 'categorie-alimentation-t4kdqt.png', alpha_es = 'C', sentence_displayed_on_product_es = '' WHERE id = 3;
UPDATE peel_categories SET nom_es = 'Muebles', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-meubles-auevpv.jpg', image_header_es = 'categorie-meubles-namk2y.png', alpha_es = 'M', sentence_displayed_on_product_es = '' WHERE id = 4;
UPDATE peel_categories SET nom_es = 'Perfume', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-parfum-7ddyu2.jpg', image_header_es = 'categorie-parfums-2hun2r.png', alpha_es = 'P', sentence_displayed_on_product_es = '' WHERE id = 5;
UPDATE peel_categories SET nom_es = 'Accesorios', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-accessoires-wats9u.jpg', image_header_es = 'categorie-accessoires-g5nsuc.png', alpha_es = 'A', sentence_displayed_on_product_es = '' WHERE id = 6;
UPDATE peel_categories SET nom_es = 'Sofás', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-fauteuils-ymntgk.jpg', image_header_es = 'categorie-fauteuils-n5ydpq.png', alpha_es = 'S', sentence_displayed_on_product_es = '' WHERE id = 7;
UPDATE peel_categories SET nom_es = 'Hombre', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-homme-ddwrwn.jpg', image_header_es = 'categorie-hommes-zqbhqk.png', alpha_es = 'H', sentence_displayed_on_product_es = '' WHERE id = 8;
UPDATE peel_categories SET nom_es = 'Mujer', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-femme-nskkqd.jpg', image_header_es = 'categorie-femmes-b8wbjy.png', alpha_es = 'M', sentence_displayed_on_product_es = '' WHERE id = 9;
UPDATE peel_categories SET nom_es = 'Sandwiches', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-sandwiches-fd7jew.jpg', image_header_es = 'categorie-sandwiches-e24jzh.png', alpha_es = 'S', sentence_displayed_on_product_es = '' WHERE id = 10;
UPDATE peel_categories SET nom_es = 'Batería de cocina', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-vaisselle-npuxmp.jpg', image_header_es = 'categorie-vaisselle-hc8jmr.png', alpha_es = 'B', sentence_displayed_on_product_es = '' WHERE id = 11;
UPDATE peel_categories SET nom_es = 'Joyería', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-bijoux-thcdxx.jpg', image_header_es = 'categorie-bijoux-nzps2p.png', alpha_es = 'J', sentence_displayed_on_product_es = '' WHERE id = 12;
UPDATE peel_categories SET nom_es = 'Objetos conectados', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-objets-connectes-rk5uxm.jpg', image_header_es = 'categorie-objets-connectes-s8nfx5.png', alpha_es = 'O', sentence_displayed_on_product_es = '' WHERE id = 13;
UPDATE peel_categories SET nom_es = 'Niños', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-enfant-8jmwpj.jpg', image_header_es = 'categorie-enfants-tue4fa.png', alpha_es = 'N', sentence_displayed_on_product_es = '' WHERE id = 14;
UPDATE peel_categories SET nom_es = 'Zapatos', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', header_html_es = '', image_es = 'categorie-chaussures-pt8kmu.jpg', image_header_es = 'categorie-chaussures-pgbpgk.png', alpha_es = 'Z', sentence_displayed_on_product_es = '' WHERE id = 15;

-- produits
UPDATE peel_produits SET nom_es = 'Sillón "Baboo"', descriptif_es = 'Un sillón con un diseño limpio. Todo el mundo habla de eso', description_es = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 10;
UPDATE peel_produits SET nom_es = 'Sujetador push-up', descriptif_es = 'Chic y cómodo, conjunto está disponible', description_es = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 11;
UPDATE peel_produits SET nom_es = 'Conjunto de 4 copas de cóctel', descriptif_es = 'Para todas las ocasiones', description_es = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 12;
UPDATE peel_produits SET nom_es = 'Anillo con perla ', descriptif_es = 'Un estilo encantador', description_es = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 13;
UPDATE peel_produits SET nom_es = 'Perfume', descriptif_es = 'Eau de Parfum', description_es = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 14;
UPDATE peel_produits SET nom_es = 'Reloj inteligente', descriptif_es = 'Siempre a tiempo, siempre en forma', description_es = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>', meta_titre_es = 'Reloj inteligente', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 15;
UPDATE peel_produits SET nom_es = 'Traje de baño 1 pieza', descriptif_es = 'calidad a bajo precio', description_es = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 16;
UPDATE peel_produits SET nom_es = 'Sándwich de pan Focaccia con tomate y ensalada', descriptif_es = 'Ligero y delicioso! El mejor sándwich del verano', description_es = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 17;
UPDATE peel_produits SET nom_es = 'Camiseta', descriptif_es = '¡Sobrio y elegante!', description_es = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 18;
UPDATE peel_produits SET nom_es = 'Auriculares con cable', descriptif_es = 'Mantente al ritmo. Compacto y diseño', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 19;
UPDATE peel_produits SET nom_es = 'Camisa de cuadros', descriptif_es = 'Para pequeños leñadores', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 20;
UPDATE peel_produits SET nom_es = 'Máquina de café Nespresso', descriptif_es = 'What else ?', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 21;
UPDATE peel_produits SET nom_es = 'Conjunto de camisa y chaqueta', descriptif_es = 'Casual y Chic', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 27;
UPDATE peel_produits SET nom_es = 'Jersey a rayas azul y blanco', descriptif_es = 'Para verdaderos marineros pequeños', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 28;
UPDATE peel_produits SET nom_es = 'Camiseta "USA"', descriptif_es = 'Un clásico atemporal', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 29;
UPDATE peel_produits SET nom_es = 'Botines suaves de color carne', descriptif_es = 'Casual chic', description_es = '', meta_titre_es = '', meta_key_es = '', meta_desc_es = '', tab1_html_es = '', tab2_html_es = '', tab3_html_es = '', tab4_html_es = '', tab5_html_es = '', tab6_html_es = '', tab1_title_es = '', tab2_title_es = '', tab3_title_es = '', tab4_title_es = '', tab5_title_es = '', tab6_title_es = '' WHERE id = 30;

-- rubriques
UPDATE peel_rubriques SET nom_es = 'Condiciones de entrega', description_es = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla laoreet dapibus risus, vitae tincidunt leo lobortis ut. Ut varius lobortis volutpat. Aenean quam elit, tempus ac viverra nec, molestie ut tortor. Fusce diam purus, lacinia facilisis mattis ac, euismod vitae metus. Etiam eu quam vel leo sollicitudin semper in eget massa. Etiam non leo congue, ultrices dui et, sodales ante. Vivamus eu sapien et lacus ornare bibendum.</p> <p>Nunc sapien ligula, dictum vitae facilisis eu, suscipit quis massa. Quisque lobortis lobortis ante, in tincidunt nibh mattis ut. Donec porttitor enim non orci iaculis vehicula. Integer placerat nunc nec mauris consectetur, eget sodales nibh lobortis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc elementum dapibus consectetur. Nunc suscipit scelerisque tincidunt. Sed euismod lobortis nulla aliquet pharetra. Pellentesque turpis nulla, gravida eu elementum non, elementum et neque. Nullam nec dapibus erat. Aenean gravida, ex ac ultricies tincidunt, felis mauris tempor mauris, sit amet egestas ex nulla vitae augue. Donec pretium fringilla condimentum. Nunc ut turpis vestibulum, lobortis turpis in, dapibus magna. Aliquam ac vulputate sapien. Phasellus vel auctor sem.</p> <p>Etiam iaculis nulla nec ligula rhoncus, non luctus erat maximus. Morbi fringilla nisl et fermentum facilisis. Phasellus ac tristique velit, vitae ornare ligula. Sed ut pellentesque tortor. Quisque ac ligula lorem. Maecenas lobortis augue eget tincidunt pulvinar. Pellentesque porta nulla felis, et tempor purus posuere vitae. Nunc fermentum velit quis magna pharetra, et semper dolor molestie. Vestibulum nec augue feugiat, blandit erat ut, sollicitudin lorem. Praesent semper egestas tortor ac eleifend.</p> <p>Sed risus ipsum, mattis ultricies enim quis, pellentesque ornare ex. In convallis nisi ac velit tincidunt, ut condimentum metus cursus. Vivamus auctor, nulla non cursus tincidunt, dui mi lobortis neque, vitae interdum eros eros vestibulum turpis. Pellentesque mollis ornare erat, vitae lobortis eros lacinia a. In hac habitasse platea dictumst. Integer id arcu hendrerit, maximus quam lobortis, ullamcorper massa. Morbi interdum sodales tincidunt. Nam imperdiet felis sem, at ultricies mauris maximus vel. Ut et arcu consectetur, luctus eros eu, tristique leo.</p><p>Praesent metus orci, vulputate nec tincidunt non, accumsan nec nunc. Praesent ac aliquam tortor. Pellentesque efficitur nulla congue orci gravida pharetra. Etiam at scelerisque dolor. Nullam eget consectetur lectus. Vestibulum ac tortor eu nibh rhoncus semper. Aenean at vehicula dui. Quisque efficitur leo in condimentum lobortis. Vivamus eu enim sed enim ullamcorper hendrerit vitae quis eros. Maecenas sit amet tincidunt magna, non tincidunt augue.</p> ', meta_titre_es = '', meta_key_es = '', meta_desc_es = '' WHERE id = 5; 

-- information légale
UPDATE `peel_legal` SET `titre_es`= 'Información legal', `texte_es` = '<div id="lipsum"> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla laoreet dapibus risus, vitae tincidunt leo lobortis ut. Ut varius lobortis volutpat. Aenean quam elit, tempus ac viverra nec, molestie ut tortor. Fusce diam purus, lacinia facilisis mattis ac, euismod vitae metus. Etiam eu quam vel leo sollicitudin semper in eget massa. Etiam non leo congue, ultrices dui et, sodales ante. Vivamus eu sapien et lacus ornare bibendum.</p> <p>Nunc sapien ligula, dictum vitae facilisis eu, suscipit quis massa. Quisque lobortis lobortis ante, in tincidunt nibh mattis ut. Donec porttitor enim non orci iaculis vehicula. Integer placerat nunc nec mauris consectetur, eget sodales nibh lobortis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc elementum dapibus consectetur. Nunc suscipit scelerisque tincidunt. Sed euismod lobortis nulla aliquet pharetra. Pellentesque turpis nulla, gravida eu elementum non, elementum et neque. Nullam nec dapibus erat. Aenean gravida, ex ac ultricies tincidunt, felis mauris tempor mauris, sit amet egestas ex nulla vitae augue. Donec pretium fringilla condimentum. Nunc ut turpis vestibulum, lobortis turpis in, dapibus magna. Aliquam ac vulputate sapien. Phasellus vel auctor sem.</p> <p>Etiam iaculis nulla nec ligula rhoncus, non luctus erat maximus. Morbi fringilla nisl et fermentum facilisis. Phasellus ac tristique velit, vitae ornare ligula. Sed ut pellentesque tortor. Quisque ac ligula lorem. Maecenas lobortis augue eget tincidunt pulvinar. Pellentesque porta nulla felis, et tempor purus posuere vitae. Nunc fermentum velit quis magna pharetra, et semper dolor molestie. Vestibulum nec augue feugiat, blandit erat ut, sollicitudin lorem. Praesent semper egestas tortor ac eleifend.</p> <p>Sed risus ipsum, mattis ultricies enim quis, pellentesque ornare ex. In convallis nisi ac velit tincidunt, ut condimentum metus cursus. Vivamus auctor, nulla non cursus tincidunt, dui mi lobortis neque, vitae interdum eros eros vestibulum turpis. Pellentesque mollis ornare erat, vitae lobortis eros lacinia a. In hac habitasse platea dictumst. Integer id arcu hendrerit, maximus quam lobortis, ullamcorper massa. Morbi interdum sodales tincidunt. Nam imperdiet felis sem, at ultricies mauris maximus vel. Ut et arcu consectetur, luctus eros eu, tristique leo.</p> <p>Praesent metus orci, vulputate nec tincidunt non, accumsan nec nunc. Praesent ac aliquam tortor. Pellentesque efficitur nulla congue orci gravida pharetra. Etiam at scelerisque dolor. Nullam eget consectetur lectus. Vestibulum ac tortor eu nibh rhoncus semper. Aenean at vehicula dui. Quisque efficitur leo in condimentum lobortis. Vivamus eu enim sed enim ullamcorper hendrerit vitae quis eros. Maecenas sit amet tincidunt magna, non tincidunt augue.</p> </div>' WHERE id=1;

-- conditions de vente
UPDATE `peel_cgv` SET `titre_es`= 'Condiciones de venta', `texte_es` = '<div id="lipsum"> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla laoreet dapibus risus, vitae tincidunt leo lobortis ut. Ut varius lobortis volutpat. Aenean quam elit, tempus ac viverra nec, molestie ut tortor. Fusce diam purus, lacinia facilisis mattis ac, euismod vitae metus. Etiam eu quam vel leo sollicitudin semper in eget massa. Etiam non leo congue, ultrices dui et, sodales ante. Vivamus eu sapien et lacus ornare bibendum.</p> <p>Nunc sapien ligula, dictum vitae facilisis eu, suscipit quis massa. Quisque lobortis lobortis ante, in tincidunt nibh mattis ut. Donec porttitor enim non orci iaculis vehicula. Integer placerat nunc nec mauris consectetur, eget sodales nibh lobortis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc elementum dapibus consectetur. Nunc suscipit scelerisque tincidunt. Sed euismod lobortis nulla aliquet pharetra. Pellentesque turpis nulla, gravida eu elementum non, elementum et neque. Nullam nec dapibus erat. Aenean gravida, ex ac ultricies tincidunt, felis mauris tempor mauris, sit amet egestas ex nulla vitae augue. Donec pretium fringilla condimentum. Nunc ut turpis vestibulum, lobortis turpis in, dapibus magna. Aliquam ac vulputate sapien. Phasellus vel auctor sem.</p> <p>Etiam iaculis nulla nec ligula rhoncus, non luctus erat maximus. Morbi fringilla nisl et fermentum facilisis. Phasellus ac tristique velit, vitae ornare ligula. Sed ut pellentesque tortor. Quisque ac ligula lorem. Maecenas lobortis augue eget tincidunt pulvinar. Pellentesque porta nulla felis, et tempor purus posuere vitae. Nunc fermentum velit quis magna pharetra, et semper dolor molestie. Vestibulum nec augue feugiat, blandit erat ut, sollicitudin lorem. Praesent semper egestas tortor ac eleifend.</p> <p>Sed risus ipsum, mattis ultricies enim quis, pellentesque ornare ex. In convallis nisi ac velit tincidunt, ut condimentum metus cursus. Vivamus auctor, nulla non cursus tincidunt, dui mi lobortis neque, vitae interdum eros eros vestibulum turpis. Pellentesque mollis ornare erat, vitae lobortis eros lacinia a. In hac habitasse platea dictumst. Integer id arcu hendrerit, maximus quam lobortis, ullamcorper massa. Morbi interdum sodales tincidunt. Nam imperdiet felis sem, at ultricies mauris maximus vel. Ut et arcu consectetur, luctus eros eu, tristique leo.</p> <p>Praesent metus orci, vulputate nec tincidunt non, accumsan nec nunc. Praesent ac aliquam tortor. Pellentesque efficitur nulla congue orci gravida pharetra. Etiam at scelerisque dolor. Nullam eget consectetur lectus. Vestibulum ac tortor eu nibh rhoncus semper. Aenean at vehicula dui. Quisque efficitur leo in condimentum lobortis. Vivamus eu enim sed enim ullamcorper hendrerit vitae quis eros. Maecenas sit amet tincidunt magna, non tincidunt augue.</p> </div>' WHERE id=1;

-- couleurs
UPDATE `peel_couleurs` SET `nom_es` = 'Rojo' WHERE id = 1;
UPDATE `peel_couleurs` SET `nom_es` = 'Negro' WHERE id = 2;